name: culos
description: A high-performance, immutable KDE Plasma distribution based on Fedora Kinoite 44.
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 44

modules:
  - type: yum-repo
    repos:
      - https://fedorainfracloud.org
      - https://rpmfusion.org
      - https://rpmfusion.org

  - type: rpm-ostree
    repos:
      - bochecha-cachyos-fedora-44
      - rpmfusion-free-release
      - rpmfusion-nonfree-release
    remove:
      - kernel
      - kernel-core
      - kernel-modules
      - kernel-modules-extra
      - plasma-discover
      - plasma-discover-flatpak
      - plasma-discover-notifier
    install:
      - kernel-cachyos
      - kernel-cachyos-core
      - kernel-cachyos-modules
      - kernel-cachyos-modules-extra
      - podman
      - distrobox
      - akmod-nvidia
      - xorg-x11-drv-nvidia-cuda
      - mesa-vulkan-drivers
      - google-sans-flex-fonts
      - papirus-icon-theme

  - type: flatpak
    remotes:
      flathub: https://flathub.org
    install:
      - io.github.kolunmi.Bazaar
      - io.github.dvlv.boxbuddyrs
